format_version: 10

pipelines:

  hello-pipeline:

    group: learning

    materials:

      code:
        git: https://github.com/saicharanreddy07/GOCD.git
        branch: main

    stages:

      - Hello:

          jobs:

            Print:

              tasks:

                - exec:
                    command: echo
                    arguments:
                      - "Hello GoCD"